package telas;

import objetos.Kernel;
import javax.swing.JFrame;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 16/10/2010, 20:27:00
 */

/**
 *
 * @author Vagner Mendes
 */
public class Iniciar extends javax.swing.JFrame {

    private Kernel kernel = null;
    /** Creates new form NewJFrame */
    public Iniciar() {     
        kernel = new Kernel(this);
        initComponents();
        
            /*
        try {
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Iniciar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Iniciar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Iniciar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Iniciar.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        botao_sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        categoria = new javax.swing.JMenuItem();
        empresa = new javax.swing.JMenuItem();
        produtos = new javax.swing.JMenuItem();
        servico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suite Multi-Desk SVM");

        jMenu1.setText("Sistema");

        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        jMenu1.add(botao_sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        categoria.setText("Categoria");
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });
        jMenu2.add(categoria);

        empresa.setText("Empresa");
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });
        jMenu2.add(empresa);

        produtos.setText("Produtos");
        produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosActionPerformed(evt);
            }
        });
        jMenu2.add(produtos);

        servico.setText("Serviço");
        servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicoActionPerformed(evt);
            }
        });
        jMenu2.add(servico);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
        kernel.Tela(1, kernel,0,null,null);
    }//GEN-LAST:event_categoriaActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botao_sairActionPerformed

    private void servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicoActionPerformed
        // TODO add your handling code here:
        kernel.Tela(2, kernel,0,null,null);
    }//GEN-LAST:event_servicoActionPerformed

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
        kernel.Tela(4, kernel,0,null,null);
    }//GEN-LAST:event_empresaActionPerformed

    private void produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosActionPerformed
        // TODO add your handling code here:
        kernel.Tela(6, kernel,0,null,null);
    }//GEN-LAST:event_produtosActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        final Iniciar iniciar = new Iniciar();
        final Kernel kernel = new Kernel(iniciar);
        Splash s = new Splash(2000);
        s.mostraTela();
        iniciar.setExtendedState(iniciar.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        kernel.Tela(0,null,2,null,null);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem botao_sair;
    private javax.swing.JMenuItem categoria;
    private javax.swing.JMenuItem empresa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem produtos;
    private javax.swing.JMenuItem servico;
    // End of variables declaration//GEN-END:variables

}
