/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatorioContaspagar.java
 *
 * Created on 25/05/2011, 19:02:39
 */

package telas;

import banco.BD_Clientes;
import banco.BD_Vendas;
import impressao.ImprimirRelatorioClientesVendas;
import impressao.ImprimirRelatorioCustos;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import objetos.Kernel;
import objetos.Cliente;
import objetos.Vendas;

/**
 *
 * @author vagnerfeijomendes
 */
public class RelatorioClientesVendas extends javax.swing.JPanel {

    private Kernel          kernel              = null;
    private Cliente         obj_Clientes        = null;
    private Vendas          obj_Vendas          = null;
    private DecimalFormat   fmt = null;
    private BD_Vendas       bd_Vendas           = null;    
    private BD_Clientes     bd_Clientes         = null;    
    private ImprimirRelatorioClientesVendas impressao   = null;
    private int acao = 0;  
    /** Creates new form RelatorioContaspagar */
    public RelatorioClientesVendas(Kernel obj,int acao,Object texto) {
        this.kernel = obj;            
        this.acao = acao;
        initComponents();
        
        bd_Vendas       = new BD_Vendas(kernel);        
        bd_Clientes     = new BD_Clientes(kernel);                       
        impressao       = new ImprimirRelatorioClientesVendas(kernel);
        
        if(acao!=0){
            obj_Clientes = bd_Clientes.getClienteID(acao);
            Cliente_id.setText(String.valueOf(obj_Clientes.getCliente_id()));
            campo_cliente.setText(obj_Clientes.getNome());            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_cadastrar_area3 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        Cliente_id = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        busca = new javax.swing.JButton();
        busca_cliente = new javax.swing.JButton();
        campo_cliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valor_total = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 241, 88));
        setForeground(new java.awt.Color(255, 241, 88));

        painel_cadastrar_area3.setBackground(new java.awt.Color(255, 241, 88));
        painel_cadastrar_area3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        voltar.setBackground(new java.awt.Color(255, 241, 88));
        voltar.setForeground(new java.awt.Color(255, 241, 88));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        voltar.setToolTipText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        imprimir.setBackground(new java.awt.Color(255, 241, 88));
        imprimir.setForeground(new java.awt.Color(255, 241, 88));
        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/impressora.png"))); // NOI18N
        imprimir.setToolTipText("Voltar");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        Cliente_id.setBackground(new java.awt.Color(255, 241, 88));
        Cliente_id.setForeground(new java.awt.Color(255, 241, 88));
        Cliente_id.setText("0");

        jLabel48.setText("Imprimir");

        jLabel49.setText("Voltar");

        org.jdesktop.layout.GroupLayout painel_cadastrar_area3Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area3);
        painel_cadastrar_area3.setLayout(painel_cadastrar_area3Layout);
        painel_cadastrar_area3Layout.setHorizontalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel49)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(imprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel48)))
                .add(18, 18, 18)
                .add(Cliente_id)
                .addContainerGap(964, Short.MAX_VALUE))
        );
        painel_cadastrar_area3Layout.setVerticalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(voltar)
                    .add(imprimir))
                .addContainerGap(31, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Cliente_id)
                    .add(jLabel48)
                    .add(jLabel49))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 241, 88));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtro"));
        jPanel1.setForeground(new java.awt.Color(255, 241, 88));

        busca.setBackground(new java.awt.Color(255, 241, 88));
        busca.setForeground(new java.awt.Color(255, 241, 88));
        busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N
        busca.setToolTipText("Salvar");
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });

        busca_cliente.setText("Busca cliente");
        busca_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_clienteActionPerformed(evt);
            }
        });

        campo_cliente.setEditable(false);

        jLabel1.setText("Cliente:");

        jLabel5.setText("Total (R$):");

        valor_total.setText("0,0");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(campo_cliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(busca_cliente))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(valor_total)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(busca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(campo_cliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(busca_cliente))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(valor_total)))
            .add(busca)
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Valor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setDragEnabled(true);
        tabela.setRowHeight(25);
        tabela.getTableHeader().setReorderingAllowed(false);
        sp.setViewportView(tabela);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(2, 2, 2)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
            .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
            .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(24,kernel,0,null,null);
}//GEN-LAST:event_voltarActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        
            // TODO add your handling code here:
            try {
                impressao.Imprimir(Integer.parseInt(Cliente_id.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(RelatorioClientesVendas.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_imprimirActionPerformed

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        // TODO add your handling code here:
        MontarTabela(Integer.parseInt(Cliente_id.getText()));
    }//GEN-LAST:event_buscaActionPerformed

    private void busca_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_clienteActionPerformed
        // TODO add your handling code here:
        kernel.Tela(31,kernel,0,null,null);
}//GEN-LAST:event_busca_clienteActionPerformed

    private void MontarTabela(int id) {
        try {
            
            Vendas[] vetor2 = null;
            
            vetor2 = bd_Vendas.getRelatorio(id);
            
            int tamanho= vetor2.length;
            String dados[][] = new String[tamanho][5];
            int coluna=0;
            
            Vendas       obj = new Vendas();
            double venda = 0.0;
            double desconto = 0.0;
            double total = 0.0;
            fmt = new DecimalFormat("#0.00");
            for(int i=0; i < vetor2.length; i++){
                coluna=0;
                obj = (Vendas)vetor2[i];
                dados[i][coluna++] = String.valueOf(obj.getVendas_id());
                dados[i][coluna++] = String.valueOf("VENDAS");     
                dados[i][coluna++] = fmt.format(obj.getPreco_venda());
                dados[i][coluna++] = new SimpleDateFormat("dd/MM/yyyy").format(obj.getData());
                dados[i][coluna++] = new SimpleDateFormat("HH:mm").format(obj.getHora());
                
                total += obj.getPreco_venda();
            }
            
            valor_total.setText(String.valueOf(total));
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                dados,
                new String [] {"Cod", "Descrição","Valor","Data"," "}){
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, 
                    java.lang.String.class,java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            coluna=0;
            tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tabela.getColumnModel().getColumn(coluna++).setPreferredWidth(50);
            tabela.getColumnModel().getColumn(coluna++).setPreferredWidth(400);        
            tabela.getColumnModel().getColumn(coluna++).setPreferredWidth(100);       
            tabela.getColumnModel().getColumn(coluna++).setPreferredWidth(100);                
            tabela.getColumnModel().getColumn(coluna++).setPreferredWidth(100);        
            
            tabela.setDragEnabled(true);
            sp.setViewportView(tabela);        
            //ButtonColumn buttonColumn0 = new ButtonColumn(table, 0);//VER
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioClientesVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente_id;
    private javax.swing.JButton busca;
    private javax.swing.JButton busca_cliente;
    private javax.swing.JTextField campo_cliente;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painel_cadastrar_area3;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel valor_total;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
