/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarFuncionario.java
 *
 * Created on 14/02/2011, 18:44:34
 */

package telas;

import banco.BD_Funcionario;
import banco.BD_Nivel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import objetos.Kernel;
import objetos.Funcionario;
import objetos.Nivel;

/**
 *
 * @author vagner
 */
public class CadastrarFuncionario extends javax.swing.JPanel {

    private Kernel       kernel;         
    private Funcionario     obj_Funcionario;    
    private Nivel           obj_Nivel;    
    private BD_Funcionario  bd_Funcionario;
    private BD_Nivel        bd_Nivel;
    
    /** Creates new form CadastrarAnimais */
    public CadastrarFuncionario(Kernel obj,int acao,Object texto) {
        kernel = obj;      
        bd_Funcionario  = new BD_Funcionario(kernel);
        bd_Nivel        = new BD_Nivel(kernel);
        
        initComponents();    
        
        /********* PREENCHENDO O VETOR Nivel *************/   
        Nivel[] Nivel_vetor = null;
        try {
                Nivel_vetor = bd_Nivel.getNivels();
            } catch (SQLException exx) {
                Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, exx);
            }
        String dados4[] = new String[Nivel_vetor.length];

        obj_Nivel = new Nivel();
        int pos4 = 0;
        for(int i=0; i < Nivel_vetor.length; i++){
            obj_Nivel = (Nivel)Nivel_vetor[i];
            dados4[i] = String.valueOf(obj_Nivel.getNome()).toUpperCase();            
            if(i==0){
                Nivel_id.setText(String.valueOf(obj_Nivel.getNivel_id()));
            }
        }
        combo_nivel.setModel(new javax.swing.DefaultComboBoxModel(dados4));        
        
        if(acao!=0){
            combo_nivel.setSelectedIndex(pos4);
        }       
        /*****************************************************************/
        
        if(acao!=0){
            try {
                PreencherFormulario(acao);
            } catch (SQLException ex) {
                Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_cadastrar_area3 = new javax.swing.JPanel();
        salvar = new javax.swing.JButton();
        Funcionario_id = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        Nivel_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campo_endereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campo_numero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo_bairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campo_cidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campo_estado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_cep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_ddd = new javax.swing.JTextField();
        campo_telefone = new javax.swing.JTextField();
        msg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campo_idt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campo_cpf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campo_login = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        combo_nivel = new javax.swing.JComboBox();
        campo_senha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        campo_adm_dia = new javax.swing.JTextField();
        campo_adm_mes = new javax.swing.JTextField();
        campo_adm_ano = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 241, 88));

        painel_cadastrar_area3.setBackground(new java.awt.Color(255, 241, 88));
        painel_cadastrar_area3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        salvar.setToolTipText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        Funcionario_id.setForeground(new java.awt.Color(255, 241, 88));
        Funcionario_id.setText("0");

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        voltar.setToolTipText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        Nivel_id.setBackground(new java.awt.Color(255, 241, 88));
        Nivel_id.setForeground(new java.awt.Color(255, 241, 88));
        Nivel_id.setText("0");

        org.jdesktop.layout.GroupLayout painel_cadastrar_area3Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area3);
        painel_cadastrar_area3.setLayout(painel_cadastrar_area3Layout);
        painel_cadastrar_area3Layout.setHorizontalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap()
                .add(salvar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(142, 142, 142)
                .add(Funcionario_id)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Nivel_id)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        painel_cadastrar_area3Layout.setVerticalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(salvar)
                    .add(voltar)
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Funcionario_id)
                            .add(Nivel_id))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 241, 88));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome:");

        jLabel2.setText("Rua/Av.:");

        jLabel3.setText("Numero:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("Estado:");

        jLabel7.setText("Cep:");

        jLabel8.setText("Telefone:");

        msg.setForeground(new java.awt.Color(255, 102, 0));
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setText("Identidade:");

        jLabel10.setText("CPF:");

        jLabel13.setText("Login:");

        jLabel14.setText("Senha:");

        jLabel15.setText("Nível acesso:");

        combo_nivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_nivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_nivelItemStateChanged(evt);
            }
        });

        jLabel11.setText("D. Admissão:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel15)
                    .add(jLabel13)
                    .add(jLabel8)
                    .add(jLabel7)
                    .add(jLabel5)
                    .add(jLabel4)
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(campo_nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(campo_adm_dia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(1, 1, 1)
                                .add(campo_adm_mes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(2, 2, 2)
                                .add(campo_adm_ano, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(campo_endereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(campo_numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(campo_bairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(campo_cidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(campo_estado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(campo_cep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, campo_idt)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                        .add(campo_ddd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(2, 2, 2)
                                        .add(campo_telefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, campo_login))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(30, 30, 30)
                                        .add(jLabel10))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(18, 18, 18)
                                        .add(jLabel14)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(campo_senha)
                                    .add(campo_cpf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(msg))
                    .add(combo_nivel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(msg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(campo_nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11)
                            .add(campo_adm_dia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(campo_adm_mes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(campo_adm_ano, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(campo_endereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3)
                            .add(campo_numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(campo_bairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(campo_cidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6)
                            .add(campo_estado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(campo_cep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(campo_ddd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(campo_telefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(campo_idt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10)
                            .add(campo_cpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(campo_login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(campo_senha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(combo_nivel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(95, 95, 95))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        Salvar();
}//GEN-LAST:event_salvarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(13, kernel,0,null,null);
}//GEN-LAST:event_voltarActionPerformed

    private void combo_nivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_nivelItemStateChanged
        // TODO add your handling code here:
        Nivel_id.setText(String.valueOf(bd_Nivel.getNivelIDNome((String)combo_nivel.getSelectedItem())));
    }//GEN-LAST:event_combo_nivelItemStateChanged

    //SALVAR Funcionario
    private void Salvar(){
        obj_Funcionario    = new Funcionario();
        obj_Nivel          = new Nivel();
        if(Funcionario_id.getText().equals("0")){            
            try {
                obj_Funcionario.setNome((campo_nome.getText().equals("")?"":campo_nome.getText()));
                obj_Funcionario.setEndereco((campo_endereco.getText().equals("")?"":campo_endereco.getText()));
                obj_Funcionario.setBairro((campo_bairro.getText().equals("")?"":campo_bairro.getText()));
                obj_Funcionario.setUf((campo_estado.getText().equals("")?"":campo_estado.getText()));
                obj_Funcionario.setCidade((campo_cidade.getText().equals("")?"":campo_cidade.getText()));
                obj_Funcionario.setCep(Integer.parseInt(campo_cep.getText().equals("")?"0":campo_cep.getText()));
                obj_Funcionario.setNumero((campo_numero.getText().equals("")?"":campo_numero.getText()));
                obj_Funcionario.setCep(Integer.parseInt((campo_cep.getText().equals("")?"0":campo_cep.getText())));
                obj_Funcionario.setDdd(Integer.parseInt((campo_ddd.getText().equals("")?"0":campo_ddd.getText())));
                obj_Funcionario.setTelefone(Integer.parseInt((campo_telefone.getText().equals("")?"0":campo_telefone.getText())));
                
                obj_Funcionario.setLogin((campo_login.getText().equals("")?"":campo_login.getText()));
                obj_Funcionario.setSenha((campo_senha.getText().equals("")?"":campo_senha.getText()));
                obj_Funcionario.setIdt(campo_idt.getText());
                obj_Funcionario.setCpf(campo_cpf.getText());
                
                obj_Nivel.setNivel_id(Integer.parseInt(Nivel_id.getText()));
                obj_Funcionario.setNivel(obj_Nivel);
                
                
                String data_adm = ((!campo_adm_ano.getText().equals(""))?campo_adm_ano.getText():"0000")+"-"+((!campo_adm_mes.getText().equals(""))?campo_adm_mes.getText():"00")+"-"+((!campo_adm_dia.getText().equals(""))?campo_adm_dia.getText():"00");
                obj_Funcionario.setData_admissao(new SimpleDateFormat("yyyy-MM-dd").parse(data_adm));
                /*
                String data_dm = ((!campo_dm_ano.getText().equals(""))?campo_dm_ano.getText():"0000")+"-"+((!campo_dm_mes.getText().equals(""))?campo_dm_mes.getText():"00")+"-"+((!campo_dm_dia.getText().equals(""))?campo_dm_dia.getText():"00");
                obj_Funcionario.setData_demissao(new SimpleDateFormat("yyyy-MM-dd").parse(data_dm));
                */
                if(!campo_nome.getText().equals("")){
                    bd_Funcionario.Salvar(obj_Funcionario);
                }
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }else{            
            try {
                obj_Funcionario.setFuncionario_id(Integer.parseInt(Funcionario_id.getText()));
                obj_Funcionario.setNome((campo_nome.getText().equals("")?"":campo_nome.getText()));
                obj_Funcionario.setEndereco((campo_endereco.getText().equals("")?"":campo_endereco.getText()));
                obj_Funcionario.setBairro((campo_bairro.getText().equals("")?"":campo_bairro.getText()));
                obj_Funcionario.setCep(Integer.parseInt(campo_cep.getText().equals("")?"0":campo_cep.getText()));
                obj_Funcionario.setUf((campo_estado.getText().equals("")?"":campo_estado.getText()));
                obj_Funcionario.setCidade((campo_cidade.getText().equals("")?"":campo_cidade.getText()));
                obj_Funcionario.setNumero((campo_numero.getText().equals("")?"":campo_numero.getText()));
                obj_Funcionario.setCep(Integer.parseInt((campo_cep.getText().equals("")?"0":campo_cep.getText())));
                obj_Funcionario.setDdd(Integer.parseInt((campo_ddd.getText().equals("")?"0":campo_ddd.getText())));
                obj_Funcionario.setTelefone(Integer.parseInt((campo_telefone.getText().equals("")?"0":campo_telefone.getText())));
                
                obj_Funcionario.setLogin((campo_login.getText().equals("")?"":campo_login.getText()));
                obj_Funcionario.setSenha((campo_senha.getText().equals("")?"":campo_senha.getText()));
                obj_Funcionario.setIdt(campo_idt.getText());
                obj_Funcionario.setCpf(campo_cpf.getText());
                
                obj_Nivel.setNivel_id(Integer.parseInt(Nivel_id.getText()));
                obj_Funcionario.setNivel(obj_Nivel);
                
                String data_adm = ((!campo_adm_ano.getText().equals(""))?campo_adm_ano.getText():"0000")+"-"+((!campo_adm_mes.getText().equals(""))?campo_adm_mes.getText():"00")+"-"+((!campo_adm_dia.getText().equals(""))?campo_adm_dia.getText():"00");
                obj_Funcionario.setData_admissao(new SimpleDateFormat("yyyy-MM-dd").parse(data_adm));
                //System.out.println(data_adm);
                 /* 
                String data_dm = ((!campo_dm_dia.getText().equals(""))?campo_dm_dia.getText():"00")+"-"+((!campo_dm_mes.getText().equals(""))?campo_dm_mes.getText():"00")+"-"+((!campo_dm_ano.getText().equals(""))?campo_dm_ano.getText():"0000");
                System.out.println(data_dm);
                obj_Funcionario.setData_demissao(new SimpleDateFormat("yyyy-MM-dd").parse(data_dm));
                */
                bd_Funcionario.Atualizar(obj_Funcionario);
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        
        kernel.Tela(13,null,0,null,null);
        
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Funcionario_id;
    private javax.swing.JLabel Nivel_id;
    private javax.swing.JTextField campo_adm_ano;
    private javax.swing.JTextField campo_adm_dia;
    private javax.swing.JTextField campo_adm_mes;
    private javax.swing.JTextField campo_bairro;
    private javax.swing.JTextField campo_cep;
    private javax.swing.JTextField campo_cidade;
    private javax.swing.JTextField campo_cpf;
    private javax.swing.JTextField campo_ddd;
    private javax.swing.JTextField campo_endereco;
    private javax.swing.JTextField campo_estado;
    private javax.swing.JTextField campo_idt;
    private javax.swing.JTextField campo_login;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_numero;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JComboBox combo_nivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JPanel painel_cadastrar_area3;
    private javax.swing.JButton salvar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    private void PreencherFormulario(int acao) throws SQLException {
        
           Funcionario_id.setText(String.valueOf(acao));               
           obj_Funcionario = bd_Funcionario.getFuncionarioID(acao);
           campo_nome.setText(obj_Funcionario.getNome());
           campo_endereco.setText(obj_Funcionario.getEndereco());
           campo_bairro.setText(obj_Funcionario.getBairro());
           campo_estado.setText(obj_Funcionario.getUf());
           campo_cpf.setText(obj_Funcionario.getCpf());
           campo_idt.setText(obj_Funcionario.getIdt());           
           campo_login.setText(obj_Funcionario.getLogin());
           campo_senha.setText(obj_Funcionario.getSenha());
           campo_cidade.setText(obj_Funcionario.getCidade());           
           campo_numero.setText(obj_Funcionario.getNumero());           
           campo_cep.setText(String.valueOf((obj_Funcionario.getCep()==0)?"":obj_Funcionario.getCep()));
           campo_ddd.setText(String.valueOf((obj_Funcionario.getDdd()==0)?"":obj_Funcionario.getDdd()));
           campo_telefone.setText(String.valueOf((obj_Funcionario.getTelefone()==0)?"":obj_Funcionario.getTelefone()));
           
           Nivel_id.setText(String.valueOf(obj_Funcionario.getNivel().getNivel_id()));
           combo_nivel.setSelectedItem(obj_Funcionario.getNivel().getNome().toUpperCase());
           
           if(obj_Funcionario.getData_admissao()!=null){
               String strdata1 = new SimpleDateFormat("dd/MM/yyyy").format(obj_Funcionario.getData_admissao());
               String vet1[] = strdata1.split("/");
               campo_adm_dia.setText(vet1[0]);
               campo_adm_mes.setText(vet1[1]);
               campo_adm_ano.setText(vet1[2]);
           }
           /*
           if(!obj_Funcionario.getData_demissao().equals("0000-00-00")){
               String strdata2 = new SimpleDateFormat("dd/MM/yyyy").format(obj_Funcionario.getData_demissao());
               String vet2[] = strdata2.split("/");
               campo_dm_dia.setText(vet2[0]);
               campo_dm_mes.setText(vet2[1]);
               campo_dm_ano.setText(vet2[2]);
           }
            * 
            */           
    }

}
