/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarAdministracao.java
 *
 * Created on 07/05/2011, 15:40:01
 */

package telas;

import objetos.Kernel;

/**
 *
 * @author vagnerfeijomendes
 */
public class AdministrarCadastro extends javax.swing.JPanel {

    private Kernel kernel;
    /** Creates new form CadastrarAdministracao */
    public AdministrarCadastro(Kernel obj,int acao,Object texto) {
        kernel = obj;            
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_cadastrar_area3 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        areas = new javax.swing.JButton();
        animal = new javax.swing.JButton();
        categorias = new javax.swing.JButton();
        censo = new javax.swing.JButton();
        coleta = new javax.swing.JButton();
        corestag = new javax.swing.JButton();
        datas = new javax.swing.JButton();
        epoca = new javax.swing.JButton();
        especies = new javax.swing.JButton();
        gordura = new javax.swing.JButton();
        medicacao = new javax.swing.JButton();
        sexo = new javax.swing.JButton();
        situacao = new javax.swing.JButton();
        temporada = new javax.swing.JButton();
        tiporecaptura = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        painel_cadastrar_area3.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        voltar.setBackground(new java.awt.Color(204, 204, 204));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        voltar.setToolTipText("Voltar");
        voltar.setBorder(null);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painel_cadastrar_area3Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area3);
        painel_cadastrar_area3.setLayout(painel_cadastrar_area3Layout);
        painel_cadastrar_area3Layout.setHorizontalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .add(voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        painel_cadastrar_area3Layout.setVerticalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(voltar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatórios"));

        areas.setBackground(new java.awt.Color(204, 204, 204));
        areas.setText("Areas");
        areas.setBorder(null);
        areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areasActionPerformed(evt);
            }
        });

        animal.setBackground(new java.awt.Color(204, 204, 204));
        animal.setText("Animal");
        animal.setBorder(null);
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });

        categorias.setBackground(new java.awt.Color(204, 204, 204));
        categorias.setText("Categorias");
        categorias.setBorder(null);
        categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasActionPerformed(evt);
            }
        });

        censo.setBackground(new java.awt.Color(204, 204, 204));
        censo.setText("Censo");
        censo.setBorder(null);
        censo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                censoActionPerformed(evt);
            }
        });

        coleta.setBackground(new java.awt.Color(204, 204, 204));
        coleta.setText("Local Coleta");
        coleta.setBorder(null);
        coleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coletaActionPerformed(evt);
            }
        });

        corestag.setBackground(new java.awt.Color(204, 204, 204));
        corestag.setText("Cores Tag");
        corestag.setBorder(null);
        corestag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corestagActionPerformed(evt);
            }
        });

        datas.setBackground(new java.awt.Color(204, 204, 204));
        datas.setText("Datas");
        datas.setBorder(null);
        datas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasActionPerformed(evt);
            }
        });

        epoca.setBackground(new java.awt.Color(204, 204, 204));
        epoca.setText("Época");
        epoca.setBorder(null);
        epoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epocaActionPerformed(evt);
            }
        });

        especies.setBackground(new java.awt.Color(204, 204, 204));
        especies.setText("Espécies");
        especies.setBorder(null);
        especies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especiesActionPerformed(evt);
            }
        });

        gordura.setBackground(new java.awt.Color(204, 204, 204));
        gordura.setText("Gordura");
        gordura.setBorder(null);
        gordura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorduraActionPerformed(evt);
            }
        });

        medicacao.setBackground(new java.awt.Color(204, 204, 204));
        medicacao.setText("Medicação");
        medicacao.setBorder(null);
        medicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicacaoActionPerformed(evt);
            }
        });

        sexo.setBackground(new java.awt.Color(204, 204, 204));
        sexo.setText("Sexo");
        sexo.setBorder(null);
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });

        situacao.setBackground(new java.awt.Color(204, 204, 204));
        situacao.setText("Situação");
        situacao.setBorder(null);
        situacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situacaoActionPerformed(evt);
            }
        });

        temporada.setBackground(new java.awt.Color(204, 204, 204));
        temporada.setText("Temporada");
        temporada.setBorder(null);
        temporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temporadaActionPerformed(evt);
            }
        });

        tiporecaptura.setBackground(new java.awt.Color(204, 204, 204));
        tiporecaptura.setText("Tipo Recaptura");
        tiporecaptura.setBorder(null);
        tiporecaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiporecapturaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(animal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(areas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(categorias, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(censo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(corestag, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(210, 210, 210)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(datas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(epoca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(especies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(gordura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(coleta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(183, 183, 183)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tiporecaptura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(temporada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(situacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(animal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(datas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(areas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(epoca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(categorias, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(especies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(situacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(censo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(gordura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(temporada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(corestag, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(coleta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tiporecaptura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(0,kernel,0,null,null);
}//GEN-LAST:event_voltarActionPerformed

    private void areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areasActionPerformed
        // TODO add your handling code here:
       kernel.Tela(1,kernel,0,null,null);
    }//GEN-LAST:event_areasActionPerformed

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
        kernel.Tela(21,kernel,0,null,null);
    }//GEN-LAST:event_animalActionPerformed

    private void categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasActionPerformed
        // TODO add your handling code here:
        kernel.Tela(6,kernel,0,null,null);
    }//GEN-LAST:event_categoriasActionPerformed

    private void censoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_censoActionPerformed
        // TODO add your handling code here:
        kernel.Tela(28,kernel,0,null,null);
    }//GEN-LAST:event_censoActionPerformed

    private void coletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coletaActionPerformed
        // TODO add your handling code here:
        kernel.Tela(9,kernel,0,null,null);
    }//GEN-LAST:event_coletaActionPerformed

    private void corestagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corestagActionPerformed
        // TODO add your handling code here:
        kernel.Tela(2,kernel,0,null,null);
    }//GEN-LAST:event_corestagActionPerformed

    private void datasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasActionPerformed
        // TODO add your handling code here:
        kernel.Tela(7,kernel,0,null,null);
    }//GEN-LAST:event_datasActionPerformed

    private void epocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epocaActionPerformed
        // TODO add your handling code here:
        kernel.Tela(14,kernel,0,null,null);
    }//GEN-LAST:event_epocaActionPerformed

    private void especiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especiesActionPerformed
        // TODO add your handling code here:
        kernel.Tela(3,kernel,0,null,null);
    }//GEN-LAST:event_especiesActionPerformed

    private void gorduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorduraActionPerformed
        // TODO add your handling code here:
        kernel.Tela(8,kernel,0,null,null);
    }//GEN-LAST:event_gorduraActionPerformed

    private void medicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicacaoActionPerformed
        // TODO add your handling code here:        
        kernel.Tela(13,kernel,0,null,null);
    }//GEN-LAST:event_medicacaoActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
        kernel.Tela(4,kernel,0,null,null);
    }//GEN-LAST:event_sexoActionPerformed

    private void situacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situacaoActionPerformed
        // TODO add your handling code here:
        kernel.Tela(5,kernel,0,null,null);
    }//GEN-LAST:event_situacaoActionPerformed

    private void temporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temporadaActionPerformed
        // TODO add your handling code here:
        kernel.Tela(10,kernel,0,null,null);
    }//GEN-LAST:event_temporadaActionPerformed

    private void tiporecapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiporecapturaActionPerformed
        // TODO add your handling code here:
        kernel.Tela(11,kernel,0,null,null);
    }//GEN-LAST:event_tiporecapturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton animal;
    private javax.swing.JButton areas;
    private javax.swing.JButton categorias;
    private javax.swing.JButton censo;
    private javax.swing.JButton coleta;
    private javax.swing.JButton corestag;
    private javax.swing.JButton datas;
    private javax.swing.JButton epoca;
    private javax.swing.JButton especies;
    private javax.swing.JButton gordura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medicacao;
    private javax.swing.JPanel painel_cadastrar_area3;
    private javax.swing.JButton sexo;
    private javax.swing.JButton situacao;
    private javax.swing.JButton temporada;
    private javax.swing.JButton tiporecaptura;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
