/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarIdade.java
 *
 * Created on 14/02/2011, 18:44:34
 */

package telas;

import banco.BD_Idade;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import objetos.Kernel;
import objetos.Idade;
import objetos.Animal;

/**
 *
 * @author vagner
 */
public class CadastrarIdade extends javax.swing.JPanel {

    private Kernel     kernel;
    private Idade      obj_Idade;
    private Animal      obj_Animal;
    private BD_Idade   bd_Idade;
    private Object     objeto;
    private int        acao;
    /** Creates new form CadastrarAnimais */
    public CadastrarIdade(Kernel obj,int acao,Object ob){
        this.objeto = ob;
        this.kernel = obj;
        this.acao   = acao;
        initComponents();                
        this.TabelaIdade();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        tabela_Idade = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        salvar_Idade = new javax.swing.JButton();
        dc_ano = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dc_mes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dc_dia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dd_dia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dd_mes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dd_ano = new javax.swing.JTextField();
        calcular_idade = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();
        Idade_id = new javax.swing.JLabel();
        Animal_id = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 204, 204));

        tabela_Idade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "D. Captura", "D. Desmame", "Idade", "Editar", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Idade.setDragEnabled(true);
        tabela_Idade.setRowHeight(25);
        tabela_Idade.getTableHeader().setReorderingAllowed(false);
        sp.setViewportView(tabela_Idade);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        salvar_Idade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        salvar_Idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_IdadeActionPerformed(evt);
            }
        });

        jLabel10.setText("/");

        jLabel11.setText("/");

        jLabel3.setText("Data Captura:");

        jLabel4.setText("Data Desmame:");

        jLabel13.setText("/");

        jLabel12.setText("/");

        jLabel2.setText("Idade(dias):");

        calcular_idade.setText("Calcular Idade");
        calcular_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_idadeActionPerformed(evt);
            }
        });

        botao_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltarActionPerformed(evt);
            }
        });

        Idade_id.setForeground(new java.awt.Color(204, 204, 204));
        Idade_id.setText("0");

        Animal_id.setForeground(new java.awt.Color(204, 204, 204));
        Animal_id.setText("0");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(dc_dia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(2, 2, 2)
                        .add(jLabel11)
                        .add(2, 2, 2)
                        .add(dc_mes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(1, 1, 1)
                        .add(jLabel10))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(idade, 0, 0, Short.MAX_VALUE)
                            .add(dd_dia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(jLabel13)
                                .add(2, 2, 2)
                                .add(dd_mes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(1, 1, 1)
                                .add(jLabel12)
                                .add(2, 2, 2)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(dd_ano, 0, 0, Short.MAX_VALUE)
                                    .add(dc_ano, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(calcular_idade)))))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                        .add(botao_voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(salvar_Idade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(Idade_id)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Animal_id)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(jLabel11)
                            .add(dc_mes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10)
                            .add(dc_dia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(jLabel13)
                            .add(dd_mes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel12)
                            .add(dd_dia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(dc_ano, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dd_ano, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(idade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(calcular_idade)))
            .add(jPanel1Layout.createSequentialGroup()
                .add(botao_voltar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Idade_id)
                    .add(Animal_id)))
            .add(salvar_Idade)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_IdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_IdadeActionPerformed
        // TODO add your handling code here:
        SalvarIdade();
}//GEN-LAST:event_salvar_IdadeActionPerformed

    private void calcular_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_idadeActionPerformed
        try {
            // TODO add your handling code here:        
            //DATA CAPTURA
            if((!dc_ano.getText().equals(""))&&(!dd_ano.getText().equals(""))){
                String sDate1 = dc_ano.getText()+"-"+dc_mes.getText()+"-"+dc_dia.getText();
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);
                
            //DATA DESMAME
            String sDate2 = dd_ano.getText()+"-"+dd_mes.getText()+"-"+dd_dia.getText();
            Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(sDate2);
            
            idade.setText(String.valueOf(((date2.getTime()-date1.getTime())/86400/1000)));
            } 
        }catch (ParseException ex) {
                Logger.getLogger(CadastrarIdade.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_calcular_idadeActionPerformed

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(21,null,2,Animal_id.getText(),null);
}//GEN-LAST:event_botao_voltarActionPerformed

    
    //SALVAR Idade
    private void SalvarIdade(){
        obj_Idade = new Idade();
        obj_Animal= new Animal();
        bd_Idade  = new BD_Idade(kernel);
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        Date date = new Date(); 
            
        if(Idade_id.getText().equals("0")){            
            
            //DATA CAPTURA
            String sDate1 = dc_ano.getText()+"-"+dc_mes.getText()+"-"+dc_dia.getText();
            try {
                obj_Idade.setData_captura(dateFormat.parse(sDate1));
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarIdade.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //DATA DESMAME
            String sDate2 = dd_ano.getText()+"-"+dd_mes.getText()+"-"+dd_dia.getText();
            try {
                obj_Idade.setData_desmame(dateFormat.parse(sDate2));
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarIdade.class.getName()).log(Level.SEVERE, null, ex);
            }

            //SETANDO ANIMAL
            obj_Animal.setAnimal_id(Integer.parseInt(Animal_id.getText()));
            obj_Idade.setAnimal(obj_Animal);
            
            //IDADE
            obj_Idade.setIdade(Integer.parseInt(idade.getText()));
            
            bd_Idade.Salvar(obj_Idade);
            
            
        }else{            
            //DATA CAPTURA
            String sDate1 = dc_ano.getText()+"-"+dc_mes.getText()+"-"+dc_dia.getText();
            try {
                obj_Idade.setData_captura(dateFormat.parse(sDate1));
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarIdade.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //DATA DESMAME
            String sDate2 = dd_ano.getText()+"-"+dd_mes.getText()+"-"+dd_dia.getText();
            try {
                obj_Idade.setData_desmame(dateFormat.parse(sDate2));
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarIdade.class.getName()).log(Level.SEVERE, null, ex);
            }

            //SETANDO ANIMAL
            obj_Animal.setAnimal_id(Integer.parseInt(Animal_id.getText()));
            obj_Idade.setAnimal(obj_Animal);
            
            //IDADE
            obj_Idade.setIdade(Integer.parseInt(idade.getText()));
            
            //SETANDO O ID
            obj_Idade.setIdade_id(Integer.parseInt(Idade_id.getText()));
            
            bd_Idade.Atualizar(obj_Idade);
        }
        
        dc_ano.setText(""); 
        dd_ano.setText(""); 
        dc_dia.setText(""); 
        dd_dia.setText(""); 
        dc_mes.setText(""); 
        dd_mes.setText("");         
        idade.setText("");         
        Idade_id.setText("0"); 
        //PREENCHER A TABELA DE DADOS COM AS ÁREAS
        TabelaIdade();
    }
    
    //TABELA Idade
    public void TabelaIdade(){
        
        if(objeto instanceof String){
            Animal_id.setText((String)objeto);
        }

        bd_Idade = new BD_Idade(kernel);
        Idade[] Idade_vetor = null;
        try {
            //VERIFICAR SE É BUSCA OU NÃO        
            Idade_vetor = bd_Idade.getIdades(Integer.parseInt(Animal_id.getText()));
        } catch (SQLException ex2) {
            Logger.getLogger(CadastrarIdade.class.getName()).log(Level.SEVERE, null, ex2);
        }
        
        
        String dados[][] = new String[Idade_vetor.length][6];

        Idade esp = new Idade();
        for(int i=0; i < Idade_vetor.length; i++){
            esp = (Idade)Idade_vetor[i];
            dados[i][0] = String.valueOf(esp.getIdade_id());   
            dados[i][1] = new SimpleDateFormat("dd/MM/yyyy").format(esp.getData_captura());            
            dados[i][2] = new SimpleDateFormat("dd/MM/yyyy").format(esp.getData_desmame());
            dados[i][3] = String.valueOf(esp.getIdade());            
            dados[i][4] = "editar";
            dados[i][5] = "excluir";            
        }
      
        
        tabela_Idade.setModel(new javax.swing.table.DefaultTableModel(
            dados,
            new String [] {"Cod", "D. Captura","D. Desmame","Idade","", ""}){
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
      
        tabela_Idade.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela_Idade.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela_Idade.getColumnModel().getColumn(1).setPreferredWidth(100);        
        tabela_Idade.getColumnModel().getColumn(2).setPreferredWidth(100);        
        tabela_Idade.getColumnModel().getColumn(3).setPreferredWidth(50);        
        tabela_Idade.getColumnModel().getColumn(4).setPreferredWidth(30);
        tabela_Idade.getColumnModel().getColumn(5).setPreferredWidth(30);
        
        tabela_Idade.setDragEnabled(true);
        sp.setViewportView(tabela_Idade);        
        //ButtonColumn buttonColumn0 = new ButtonColumn(table, 0);//VER
        ButtonColumnIdade buttonColumnIdade1 = new ButtonColumnIdade(tabela_Idade, 4);//EDITAR
        ButtonColumnIdade buttonColumnIdade2 = new ButtonColumnIdade(tabela_Idade, 5);//EXCLUIR
    }

    //CLASSE BUTTONCOLUMN Idade
    class ButtonColumnIdade extends AbstractCellEditor
         implements TableCellRenderer, TableCellEditor, ActionListener
     {
         JTable table;
         JButton renderButton;
         JButton editButton;
         String text;

         public ButtonColumnIdade(JTable table, int column)
         {
             super();
             this.table = table;
             renderButton = new JButton();

             editButton = new JButton();
             
             editButton.setFocusPainted( false );
             editButton.addActionListener( this );

             TableColumnModel columnModel = table.getColumnModel();
             columnModel.getColumn(column).setCellRenderer( this );
             columnModel.getColumn(column).setCellEditor( this );
         }

         public Component getTableCellRendererComponent(
             JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
         {
             if (hasFocus)
             {
                 renderButton.setForeground(table.getForeground());
                 renderButton.setBackground(UIManager.getColor("Button.background"));
             }
             else if (isSelected)
             {
                 renderButton.setForeground(table.getSelectionForeground());
                 renderButton.setBackground(table.getSelectionBackground());
            }
             else
             {
                 renderButton.setForeground(table.getForeground());
                 renderButton.setBackground(UIManager.getColor("Button.background"));
             }

             renderButton.setBackground(new java.awt.Color(255, 255, 255));
             renderButton.setBorder(null);
             renderButton.setBorderPainted(false);
             renderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

             text = (value == null) ? "" : value.toString();
             String imagem1 = text.equals("excluir")?"lixeira":"editar";
             renderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/"+imagem1+".png")));
             return renderButton;
         }

         public Component getTableCellEditorComponent(
             JTable table, Object value, boolean isSelected, int row, int column)
         {
             text = (value == null) ? "" : value.toString();             
             String imagem2 = text.equals("excluir")?"lixeira":"editar";
             editButton.setBackground(new java.awt.Color(255, 255, 255));
             editButton.setBorder(null);
             editButton.setBorderPainted(false);             
             editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/"+imagem2+".png")));
             editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
             //editButton.setText( text );
             return editButton;
         }

         public Object getCellEditorValue()
         {
             return text;
        }

         public void actionPerformed(ActionEvent e)
         {
             fireEditingStopped();

             switch(table.getSelectedColumn()){
                 case 5:
                     SolicitaConfirmacaoIdade();
                     TabelaIdade();
                 break;
                 case 4:
                     int id_reg = Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString());
                     obj_Idade = bd_Idade.getIdadeID(id_reg);
                     //DATA DO CAPTURA  
                     String strCaptura = new SimpleDateFormat("dd/MM/yyyy").format(obj_Idade.getData_captura());
                     String vet1[] = strCaptura.split("/");
                     
                     dc_dia.setText(vet1[0]);
                     dc_mes.setText(vet1[1]);
                     dc_ano.setText(vet1[2]);
                     
                     //DATA DO DESMAME
                     String strDesmame = new SimpleDateFormat("dd/MM/yyyy").format(obj_Idade.getData_desmame());
                     String vet2[] = strDesmame.split("/");
                     
                     dd_dia.setText(vet2[0]);
                     dd_mes.setText(vet2[1]);
                     dd_ano.setText(vet2[2]);
                     
                     //IDADE
                     idade.setText(String.valueOf(obj_Idade.getIdade()));
                     
                     //ID
                     Idade_id.setText(String.valueOf(obj_Idade.getIdade_id()));
                 break;
                 default:
                     kernel.Tela(0, kernel, 0,null,null);
                 break;
             }
             //System.out.println( "DADOS : " + table.getSelectedRow()+" "+" "+table.getSelectedColumn()+" "+table.getColumnCount()+" "+table.getValueAt(table.getSelectedRow(),0));
             
         }
     }
    private void SolicitaConfirmacaoIdade(){
     boolean escolha = false;

     Object[] options = {"Sim",
                    "Não"};
    int resposta = JOptionPane.showOptionDialog(this,
        "Desejas excluir o registro ?",
        "Exclusão",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE,
        null,     //do not use a custom Icon
        options,  //the titles of buttons
        options[1]);
     
     if (resposta == 0) {
       bd_Idade.Excluir(Integer.parseInt(tabela_Idade.getValueAt(tabela_Idade.getSelectedRow(),0).toString()));
     }
     
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Animal_id;
    private javax.swing.JLabel Idade_id;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JButton calcular_idade;
    private javax.swing.JTextField dc_ano;
    private javax.swing.JTextField dc_dia;
    private javax.swing.JTextField dc_mes;
    private javax.swing.JTextField dd_ano;
    private javax.swing.JTextField dd_dia;
    private javax.swing.JTextField dd_mes;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton salvar_Idade;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tabela_Idade;
    // End of variables declaration//GEN-END:variables

}
