/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarMedicacao.java
 *
 * Created on 14/02/2011, 18:44:34
 */

package telas;

import banco.BD_Medicacao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import objetos.Kernel;
import objetos.Medicacao;

/**
 *
 * @author vagner
 */
public class CadastrarMedicacao extends javax.swing.JPanel {

    private Kernel         kernel;         
    private Medicacao      Medicacao;    
    private BD_Medicacao   bd_Medicacao;
    private Object         objeto;
    private int            acao;
    private final int      editar       = 3;
    private final int      excluir      = 4;    
    private final int      selecionar   = 5;
    /** Creates new form CadastrarAnimais */
    public CadastrarMedicacao(Kernel obj,int acao,Object ob) {
        this.kernel = obj;
        this.objeto = ob;
        this.acao   = acao;
        initComponents();                
        this.TabelaMedicacao();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        tabela_Medicacao = new javax.swing.JTable();
        painel_cadastrar_area3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nome_Medicacao = new javax.swing.JTextField();
        Medicacao_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        concentracao_Medicacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        painel_cadastrar_area4 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        salvar_Medicacao = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        tabela_Medicacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "%", "Editar", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Medicacao.setDragEnabled(true);
        tabela_Medicacao.setRowHeight(25);
        tabela_Medicacao.getTableHeader().setReorderingAllowed(false);
        sp.setViewportView(tabela_Medicacao);

        painel_cadastrar_area3.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Nome:");

        nome_Medicacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_MedicacaoKeyPressed(evt);
            }
        });

        Medicacao_id.setForeground(new java.awt.Color(204, 204, 204));
        Medicacao_id.setText("0");

        jLabel5.setText("Concentração:");

        concentracao_Medicacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                concentracao_MedicacaoKeyPressed(evt);
            }
        });

        jLabel1.setText("%");

        org.jdesktop.layout.GroupLayout painel_cadastrar_area3Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area3);
        painel_cadastrar_area3.setLayout(painel_cadastrar_area3Layout);
        painel_cadastrar_area3Layout.setHorizontalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel4)
                        .add(1, 1, 1)
                        .add(nome_Medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Medicacao_id, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(jLabel5)
                        .add(1, 1, 1)
                        .add(concentracao_Medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(2, 2, 2)
                        .add(jLabel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        painel_cadastrar_area3Layout.setVerticalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(nome_Medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Medicacao_id))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(concentracao_Medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_cadastrar_area4.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        voltar.setBackground(new java.awt.Color(204, 204, 204));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        voltar.setToolTipText("Voltar");
        voltar.setBorder(null);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        salvar_Medicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        salvar_Medicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_MedicacaoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painel_cadastrar_area4Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area4);
        painel_cadastrar_area4.setLayout(painel_cadastrar_area4Layout);
        painel_cadastrar_area4Layout.setHorizontalGroup(
            painel_cadastrar_area4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area4Layout.createSequentialGroup()
                .add(3, 3, 3)
                .add(salvar_Medicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_cadastrar_area4Layout.setVerticalGroup(
            painel_cadastrar_area4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(voltar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(painel_cadastrar_area4Layout.createSequentialGroup()
                .add(salvar_Medicacao)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(painel_cadastrar_area4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nome_MedicacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_MedicacaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            SalvarMedicacao();
        }
}//GEN-LAST:event_nome_MedicacaoKeyPressed

    private void salvar_MedicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_MedicacaoActionPerformed
        // TODO add your handling code here:
        SalvarMedicacao();
}//GEN-LAST:event_salvar_MedicacaoActionPerformed

    private void concentracao_MedicacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_concentracao_MedicacaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            SalvarMedicacao();
        }
    }//GEN-LAST:event_concentracao_MedicacaoKeyPressed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(42, kernel, 0, null, null);
    }//GEN-LAST:event_voltarActionPerformed

    //SALVAR Medicacao
    private void SalvarMedicacao(){
        Medicacao     = new Medicacao();
        bd_Medicacao  = new BD_Medicacao(kernel);
        
        if(Medicacao_id.getText().equals("0")){
            Medicacao.setNome(nome_Medicacao.getText());
            Medicacao.setConcentracao(Double.parseDouble(concentracao_Medicacao.getText()));
            if(!nome_Medicacao.getText().equals("")){
                bd_Medicacao.Salvar(Medicacao);
            }
            
        }else{            
            Medicacao.setNome(nome_Medicacao.getText());
            Medicacao.setMedicacao_id(Integer.parseInt(Medicacao_id.getText()));
            Medicacao.setConcentracao(Double.parseDouble(concentracao_Medicacao.getText()));
            bd_Medicacao.Atualizar(Medicacao);
        }
        
        nome_Medicacao.setText(""); 
        concentracao_Medicacao.setText(""); 
        Medicacao_id.setText("0"); 
        //PREENCHER A TABELA DE DADOS COM AS ÁREAS
        TabelaMedicacao();
    }
    
    //TABELA Medicacao
    public void TabelaMedicacao(){
        
        bd_Medicacao = new BD_Medicacao(kernel);
        Medicacao[] Medicacao_vetor = null;
        try {
            //VERIFICAR SE É BUSCA OU NÃO        
            Medicacao_vetor = bd_Medicacao.getMedicacaos();
        } catch (SQLException ex2) {
            Logger.getLogger(CadastrarMedicacao.class.getName()).log(Level.SEVERE, null, ex2);
        }
        
        
        String dados[][] = new String[Medicacao_vetor.length][((acao==1)?6:5)];

        Medicacao esp = new Medicacao();
        for(int i=0; i < Medicacao_vetor.length; i++){
            esp = (Medicacao)Medicacao_vetor[i];
            dados[i][0] = String.valueOf(esp.getMedicacao_id());
            dados[i][1] = esp.getNome();  
            dados[i][2] = String.valueOf(esp.getConcentracao());  
            if(acao==1){                
                dados[i][editar] = "editar";
                if(kernel.getUsuario().getNivel()==0){        
                dados[i][excluir] = "excluir";
                }
                dados[i][selecionar] = "selecionar";
            }else{
                dados[i][editar] = "editar";
                if(kernel.getUsuario().getNivel()==0){        
                dados[i][excluir] = "excluir";
                }
            } 
         
        }
      
        
        tabela_Medicacao.setModel(new javax.swing.table.DefaultTableModel(
            dados,
            ((acao==1)?(new String [] {"Cod", "Nome","%","","", ""}):(new String [] {"Cod", "Nome","%","", ""}))){            
            Class[] types = new Class [] {
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class,                                 
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
      
        tabela_Medicacao.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela_Medicacao.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela_Medicacao.getColumnModel().getColumn(1).setPreferredWidth(270);
        tabela_Medicacao.getColumnModel().getColumn(2).setPreferredWidth(40);
        
        if(acao==1){
            tabela_Medicacao.getColumnModel().getColumn(editar).setPreferredWidth(30);
            if(kernel.getUsuario().getNivel()==0){        
            tabela_Medicacao.getColumnModel().getColumn(excluir).setPreferredWidth(30);
            }
            tabela_Medicacao.getColumnModel().getColumn(selecionar).setPreferredWidth(30);
        }else{
            tabela_Medicacao.getColumnModel().getColumn(editar).setPreferredWidth(30);
            if(kernel.getUsuario().getNivel()==0){        
            tabela_Medicacao.getColumnModel().getColumn(excluir).setPreferredWidth(30);
            }
        }
        
        tabela_Medicacao.setDragEnabled(true);
        sp.setViewportView(tabela_Medicacao);        
        //ButtonColumn buttonColumn0 = new ButtonColumn(table, 0);//VER
        if(acao==1){
            ButtonColumnMedicacao button1 = new ButtonColumnMedicacao(tabela_Medicacao, editar);//EDITAR
            if(kernel.getUsuario().getNivel()==0){        
            ButtonColumnMedicacao button2 = new ButtonColumnMedicacao(tabela_Medicacao, excluir);//EDITAR
            }
            ButtonColumnMedicacao button3 = new ButtonColumnMedicacao(tabela_Medicacao, selecionar);//SELECIONAR
        }else{
            ButtonColumnMedicacao button1 = new ButtonColumnMedicacao(tabela_Medicacao, editar);//EDITAR
            if(kernel.getUsuario().getNivel()==0){        
            ButtonColumnMedicacao button2 = new ButtonColumnMedicacao(tabela_Medicacao, excluir);//EXCLUIR
            }
        }
    }

    //CLASSE BUTTONCOLUMN Medicacao
    class ButtonColumnMedicacao extends AbstractCellEditor
         implements TableCellRenderer, TableCellEditor, ActionListener
     {
         JTable table;
         JButton renderButton;
         JButton editButton;
         String text;

         public ButtonColumnMedicacao(JTable table, int column)
         {
             super();
             this.table = table;
             renderButton = new JButton();

             editButton = new JButton();
             
             editButton.setFocusPainted( false );
             editButton.addActionListener( this );

             TableColumnModel columnModel = table.getColumnModel();
             columnModel.getColumn(column).setCellRenderer( this );
             columnModel.getColumn(column).setCellEditor( this );
         }

         public Component getTableCellRendererComponent(
             JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
         {
             if (hasFocus)
             {
                 renderButton.setForeground(table.getForeground());
                 renderButton.setBackground(UIManager.getColor("Button.background"));
             }
             else if (isSelected)
             {
                 renderButton.setForeground(table.getSelectionForeground());
                 renderButton.setBackground(table.getSelectionBackground());
            }
             else
             {
                 renderButton.setForeground(table.getForeground());
                 renderButton.setBackground(UIManager.getColor("Button.background"));
             }

             renderButton.setBackground(new java.awt.Color(255, 255, 255));
             renderButton.setBorder(null);
             renderButton.setBorderPainted(false);
             renderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

             text = (value == null) ? "" : value.toString();
             String imagem1 = "";
             if(text.equals("selecionar")){
                 imagem1 = "select";
             }else{
                 imagem1 = text.equals("excluir")?"lixeira":"editar";
             }
             renderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/"+imagem1+".png")));
             return renderButton;
         }

         public Component getTableCellEditorComponent(
             JTable table, Object value, boolean isSelected, int row, int column)
         {
             text = (value == null) ? "" : value.toString();             
             String imagem2 = text.equals("excluir")?"lixeira":"editar";
             editButton.setBackground(new java.awt.Color(255, 255, 255));
             editButton.setBorder(null);
             editButton.setBorderPainted(false);             
             editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/"+imagem2+".png")));
             editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
             //editButton.setText( text );
             return editButton;
         }

         public Object getCellEditorValue()
         {
             return text;
        }

         public void actionPerformed(ActionEvent e)
         {
             fireEditingStopped();

             switch(table.getSelectedColumn()){
                 case excluir:
                     SolicitaConfirmacaoMedicacao();
                     TabelaMedicacao();
                 break;
                 case editar:
                     int id_reg = Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString());
                     Medicacao = bd_Medicacao.getMedicacaoID(id_reg);
                     nome_Medicacao.setText(Medicacao.getNome());
                     Medicacao_id.setText(String.valueOf(Medicacao.getMedicacao_id()));
                     concentracao_Medicacao.setText(String.valueOf(Medicacao.getConcentracao()));
                 break;
                 case selecionar:
                     kernel.Tela(16, kernel,Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString()),objeto,null);
                 break;  
                 default:
                     kernel.Tela(0, kernel, 0,null,null);
                 break;
             }
             //System.out.println( "DADOS : " + table.getSelectedRow()+" "+" "+table.getSelectedColumn()+" "+table.getColumnCount()+" "+table.getValueAt(table.getSelectedRow(),0));
             
         }
     }
    private void SolicitaConfirmacaoMedicacao(){
     boolean escolha = false;

     Object[] options = {"Sim",
                    "Não"};
    int resposta = JOptionPane.showOptionDialog(this,
        "Desejas excluir o registro ?",
        "Exclusão",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE,
        null,     //do not use a custom Icon
        options,  //the titles of buttons
        options[1]);
     
     if (resposta == 0) {
       bd_Medicacao.Excluir(Integer.parseInt(tabela_Medicacao.getValueAt(tabela_Medicacao.getSelectedRow(),0).toString()));
     }
     
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Medicacao_id;
    private javax.swing.JTextField concentracao_Medicacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nome_Medicacao;
    private javax.swing.JPanel painel_cadastrar_area3;
    private javax.swing.JPanel painel_cadastrar_area4;
    private javax.swing.JButton salvar_Medicacao;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tabela_Medicacao;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
