/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarTemporada.java
 *
 * Created on 14/02/2011, 18:44:34
 */

package telas;

import banco.BD_Temporada;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import objetos.Kernel;
import objetos.Temporada;

/**
 *
 * @author vagner
 */
public class CadastrarTemporada extends javax.swing.JPanel {

    private Kernel         kernel;         
    private Temporada      obj_Temporada;    
    private BD_Temporada   bd_Temporada;
    private Object         objeto;
    private int            acao;
    
    /** Creates new form CadastrarAnimais */
    public CadastrarTemporada(Kernel obj,int acao,Object ob) {
        this.kernel = obj;
        this.objeto = ob;
        this.acao   = acao;
        initComponents();                
        this.TabelaTemporada();       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        tabela_Temporada = new javax.swing.JTable();
        painel_cadastrar_area3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nome_Temporada = new javax.swing.JTextField();
        Temporada_id = new javax.swing.JLabel();
        painel_cadastrar_area4 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        salvar_Temporada = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        tabela_Temporada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Editar", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Temporada.setDragEnabled(true);
        tabela_Temporada.setRowHeight(25);
        tabela_Temporada.getTableHeader().setReorderingAllowed(false);
        sp.setViewportView(tabela_Temporada);

        painel_cadastrar_area3.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Temporada:");

        nome_Temporada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_TemporadaKeyPressed(evt);
            }
        });

        Temporada_id.setForeground(new java.awt.Color(204, 204, 204));
        Temporada_id.setText("0");

        org.jdesktop.layout.GroupLayout painel_cadastrar_area3Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area3);
        painel_cadastrar_area3.setLayout(painel_cadastrar_area3Layout);
        painel_cadastrar_area3Layout.setHorizontalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nome_Temporada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Temporada_id, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70))
        );
        painel_cadastrar_area3Layout.setVerticalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nome_Temporada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(Temporada_id))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_cadastrar_area4.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        voltar.setBackground(new java.awt.Color(204, 204, 204));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        voltar.setToolTipText("Voltar");
        voltar.setBorder(null);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        salvar_Temporada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        salvar_Temporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_TemporadaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painel_cadastrar_area4Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area4);
        painel_cadastrar_area4.setLayout(painel_cadastrar_area4Layout);
        painel_cadastrar_area4Layout.setHorizontalGroup(
            painel_cadastrar_area4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area4Layout.createSequentialGroup()
                .add(salvar_Temporada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_cadastrar_area4Layout.setVerticalGroup(
            painel_cadastrar_area4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(voltar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(painel_cadastrar_area4Layout.createSequentialGroup()
                .add(salvar_Temporada)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .add(painel_cadastrar_area4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nome_TemporadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_TemporadaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            SalvarTemporada();
        }
}//GEN-LAST:event_nome_TemporadaKeyPressed

    private void salvar_TemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_TemporadaActionPerformed
        // TODO add your handling code here:
        SalvarTemporada();
}//GEN-LAST:event_salvar_TemporadaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(42, kernel, 0, null, null);
    }//GEN-LAST:event_voltarActionPerformed

    //SALVAR Temporada
    private void SalvarTemporada(){
        obj_Temporada     = new Temporada();
        bd_Temporada  = new BD_Temporada(kernel);
        
        if(Temporada_id.getText().equals("0")){
            obj_Temporada.setNome(nome_Temporada.getText());
            if(!nome_Temporada.getText().equals("")){
                bd_Temporada.Salvar(obj_Temporada);
            }
            
        }else{            
            obj_Temporada.setNome(nome_Temporada.getText());
            obj_Temporada.setTemporada_id(Integer.parseInt(Temporada_id.getText()));
            bd_Temporada.Atualizar(obj_Temporada);
        }
        
        nome_Temporada.setText(""); 
        Temporada_id.setText("0"); 
        //PREENCHER A TABELA DE DADOS COM AS ÁREAS
        TabelaTemporada();
    }
    
    //TABELA Temporada
    public void TabelaTemporada(){
        
        bd_Temporada = new BD_Temporada(kernel);
        Temporada[] Temporada_vetor = null;
        try {
            //VERIFICAR SE É BUSCA OU NÃO        
            Temporada_vetor = bd_Temporada.getTemporadas();
        } catch (SQLException ex2) {
            Logger.getLogger(CadastrarTemporada.class.getName()).log(Level.SEVERE, null, ex2);
        }
        
        
        String dados[][] = new String[Temporada_vetor.length][((acao==1)?5:4)];

        Temporada esp = new Temporada();
        for(int i=0; i < Temporada_vetor.length; i++){
            esp = (Temporada)Temporada_vetor[i];
            dados[i][0] = String.valueOf(esp.getTemporada_id());
            dados[i][1] = String.valueOf(esp.getNome());       
            if(acao==1){                
                dados[i][2] = "editar";
                if(kernel.getUsuario().getNivel()==0){         
                dados[i][3] = "excluir";
                }
                dados[i][4] = "selecionar";
            }else{
                dados[i][2] = "editar";
                if(kernel.getUsuario().getNivel()==0){         
                dados[i][3] = "excluir";
                }
            }
            
         
        }
      
        
        tabela_Temporada.setModel(new javax.swing.table.DefaultTableModel(
            dados,                
            ((acao==1)?(new String [] {"Cod", "Temporada","","", ""}):(new String [] {"Cod", "Temporada","", ""}))){
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
      
        tabela_Temporada.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela_Temporada.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela_Temporada.getColumnModel().getColumn(1).setPreferredWidth(300);
        
        if(acao==1){
            tabela_Temporada.getColumnModel().getColumn(2).setPreferredWidth(30);
            if(kernel.getUsuario().getNivel()==0){         
            tabela_Temporada.getColumnModel().getColumn(3).setPreferredWidth(30);
            }
            tabela_Temporada.getColumnModel().getColumn(4).setPreferredWidth(30);
        }else{
            tabela_Temporada.getColumnModel().getColumn(2).setPreferredWidth(30);
            if(kernel.getUsuario().getNivel()==0){         
            tabela_Temporada.getColumnModel().getColumn(3).setPreferredWidth(30);
            }
        }
        
        
        
        tabela_Temporada.setDragEnabled(true);
        sp.setViewportView(tabela_Temporada);        
        //ButtonColumn buttonColumn0 = new ButtonColumn(table, 0);//VER
        if(acao==1){
            ButtonColumnTemporada buttonColumnTemporada1 = new ButtonColumnTemporada(tabela_Temporada, 2);//EDITAR
            if(kernel.getUsuario().getNivel()==0){         
            ButtonColumnTemporada buttonColumnTemporada2 = new ButtonColumnTemporada(tabela_Temporada, 3);//EDITAR
            }
            ButtonColumnTemporada buttonColumnTemporada3 = new ButtonColumnTemporada(tabela_Temporada, 4);//SELECIONAR
        }else{
            ButtonColumnTemporada buttonColumnTemporada1 = new ButtonColumnTemporada(tabela_Temporada, 2);//EDITAR
            if(kernel.getUsuario().getNivel()==0){         
            ButtonColumnTemporada buttonColumnTemporada2 = new ButtonColumnTemporada(tabela_Temporada, 3);//EXCLUIR
            }
        }
        
    }

    //CLASSE BUTTONCOLUMN Temporada
    class ButtonColumnTemporada extends AbstractCellEditor
         implements TableCellRenderer, TableCellEditor, ActionListener
     {
         JTable table;
         JButton renderButton;
         JButton editButton;
         String text;

         public ButtonColumnTemporada(JTable table, int column)
         {
             super();
             this.table = table;
             renderButton = new JButton();

             editButton = new JButton();
             
             editButton.setFocusPainted( false );
             editButton.addActionListener( this );

             TableColumnModel columnModel = table.getColumnModel();
             columnModel.getColumn(column).setCellRenderer( this );
             columnModel.getColumn(column).setCellEditor( this );
         }

         public Component getTableCellRendererComponent(
             JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
         {
             if (hasFocus)
             {
                 renderButton.setForeground(table.getForeground());
                 renderButton.setBackground(UIManager.getColor("Button.background"));
             }
             else if (isSelected)
             {
                 renderButton.setForeground(table.getSelectionForeground());
                 renderButton.setBackground(table.getSelectionBackground());
            }
             else
             {
                 renderButton.setForeground(table.getForeground());
                 renderButton.setBackground(UIManager.getColor("Button.background"));
             }

             renderButton.setBackground(new java.awt.Color(255, 255, 255));
             renderButton.setBorder(null);
             renderButton.setBorderPainted(false);
             renderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

             text = (value == null) ? "" : value.toString();
             String imagem1 = "";
             if(text.equals("selecionar")){
                 imagem1 = "select";
             }else{
                 imagem1 = text.equals("excluir")?"lixeira":"editar";
             }             
             renderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/"+imagem1+".png")));
             return renderButton;
         }

         public Component getTableCellEditorComponent(
             JTable table, Object value, boolean isSelected, int row, int column)
         {
             text = (value == null) ? "" : value.toString();             
             String imagem2 = text.equals("excluir")?"lixeira":"editar";
             editButton.setBackground(new java.awt.Color(255, 255, 255));
             editButton.setBorder(null);
             editButton.setBorderPainted(false);             
             editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/"+imagem2+".png")));
             editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
             //editButton.setText( text );
             return editButton;
         }

         public Object getCellEditorValue()
         {
             return text;
        }

         public void actionPerformed(ActionEvent e)
         {
             fireEditingStopped();

             switch(table.getSelectedColumn()){
                 case 3:
                     SolicitaConfirmacaoTemporada();
                     TabelaTemporada();
                 break;
                 case 2:
                     int id_reg = Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString());
                     obj_Temporada = bd_Temporada.getTemporadaID(id_reg);
                     nome_Temporada.setText(obj_Temporada.getNome());
                     Temporada_id.setText(String.valueOf(obj_Temporada.getTemporada_id()));
                 break;
                 case 4:
                     kernel.Tela(14, kernel,Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString()),objeto,null);
                 break;
                 default:
                     kernel.Tela(0, kernel, 0,objeto,null);
                 break;
             }
             //System.out.println( "DADOS : " + table.getSelectedRow()+" "+" "+table.getSelectedColumn()+" "+table.getColumnCount()+" "+table.getValueAt(table.getSelectedRow(),0));
             
         }
     }
    private void SolicitaConfirmacaoTemporada(){
     boolean escolha = false;

     Object[] options = {"Sim",
                    "Não"};
    int resposta = JOptionPane.showOptionDialog(this,
        "Desejas excluir o registro ?",
        "Exclusão",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE,
        null,     //do not use a custom Icon
        options,  //the titles of buttons
        options[1]);
     
     if (resposta == 0) {
       bd_Temporada.Excluir(Integer.parseInt(tabela_Temporada.getValueAt(tabela_Temporada.getSelectedRow(),0).toString()));
     }
     
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Temporada_id;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nome_Temporada;
    private javax.swing.JPanel painel_cadastrar_area3;
    private javax.swing.JPanel painel_cadastrar_area4;
    private javax.swing.JButton salvar_Temporada;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tabela_Temporada;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
