/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FiltroAnimal.java
 *
 * Created on 27/02/2011, 10:36:53
 */

package telas;

import banco.*;
import objetos.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
/**
 *
 * @author vagner
 */
public class FiltroCenso extends javax.swing.JPanel {

    /** Creates new form FiltroAnimal */    
    private Object              objeto;
    private int                 acao;
    private Kernel              kernel; 
    private Animal              obj_Animal;
    private Especie             obj_Especie;
    private Status              obj_Status;
    private Area                obj_Area;
    private Censo               obj_Censo;
    private Data                obj_Data;
    private AnimalTag           obj_AnimalTag;
    private Sexo                obj_Sexo;
    private Idade               obj_Idade;    
    private Anestesia           obj_Anestesia;    
    private Medicacao           obj_Medicacao;    
    private Recaptura           obj_Recaptura;
    private Epoca               obj_Epoca;
    private Sangue              obj_Sangue;
    private TipoRecaptura       obj_TipoRecaptura;
    private Gordura             obj_Gordura;    
    private Carrapato           obj_Carrapato;    
    private LocalColeta         obj_Local_Coleta;    
    private GorduraDestino      obj_Gordura_Destino; 
    private Tag                 obj_Tag; 
    private CorTag              obj_CorTag; 
    private BD_Especie          bd_Especie;
    private BD_Status           bd_Status;
    private BD_Area             bd_Area;
    private BD_Censo            bd_Censo;    
    private BD_Sexo             bd_Sexo;
    private BD_Censo_Observacao bd_Censo_Observacao;
    private BD_Data             bd_Data;
    private BD_LocalColeta      bd_LocalColeta;
    private BD_GorduraDestino   bd_GorduraDestino;
    private BD_Medicacao        bd_Medicacao;
    private BD_Epoca            bd_Epoca;
    private BD_TipoRecaptura    bd_TipoRecaptura;
    private BD_CorTag           bd_CorTag;
    private BD_AnimalCenso      bd_AnimalCenso;
    
    public FiltroCenso(Kernel obj,int acao,Object ob) {
        this.kernel = obj;
        this.objeto = ob;
        this.acao   = acao;
        
        bd_Especie          = new BD_Especie(kernel);
        bd_Status           = new BD_Status(kernel);
        bd_Area             = new BD_Area(kernel);
        bd_Sexo             = new BD_Sexo(kernel);
        bd_Censo            = new BD_Censo(kernel);
        bd_LocalColeta      = new BD_LocalColeta(kernel);
        bd_GorduraDestino   = new BD_GorduraDestino(kernel);
        bd_Medicacao        = new BD_Medicacao(kernel);
        bd_Status        = new BD_Status(kernel);
        bd_Data             = new BD_Data(kernel);
        bd_Epoca            = new BD_Epoca(kernel);
        bd_TipoRecaptura    = new BD_TipoRecaptura(kernel);
        bd_Censo_Observacao = new BD_Censo_Observacao(kernel);
        bd_AnimalCenso      = new BD_AnimalCenso(kernel);
        initComponents(); 
        PreecherFormulario();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_cadastrar_area3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_Especie = new javax.swing.JComboBox();
        combo_Status = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        combo_Area = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        combo_Sexo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campo_quantidade = new javax.swing.JTextField();
        Especie_id = new javax.swing.JLabel();
        Status_id = new javax.swing.JLabel();
        Area_id = new javax.swing.JLabel();
        Sexo_id = new javax.swing.JLabel();
        combo_Data = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Data_id = new javax.swing.JLabel();
        Censo_id = new javax.swing.JLabel();
        botao_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        sp = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_observacao = new javax.swing.JTextArea();
        painel_cadastrar_area9 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        painel_cadastrar_area3.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Formulário Simples"));

        jLabel1.setText("Espécies:");

        combo_Especie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_Especie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_EspecieItemStateChanged(evt);
            }
        });

        combo_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_Status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_StatusItemStateChanged(evt);
            }
        });

        jLabel3.setText("Situação:");

        combo_Area.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_Area.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_AreaItemStateChanged(evt);
            }
        });

        jLabel5.setText("Area:");

        combo_Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_Sexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_SexoItemStateChanged(evt);
            }
        });

        jLabel6.setText("Sexo:");

        jLabel10.setText("Quantidade:");

        Especie_id.setForeground(new java.awt.Color(204, 204, 204));
        Especie_id.setText("0");

        Status_id.setForeground(new java.awt.Color(204, 204, 204));
        Status_id.setText("0");

        Area_id.setForeground(new java.awt.Color(204, 204, 204));
        Area_id.setText("0");

        Sexo_id.setForeground(new java.awt.Color(204, 204, 204));
        Sexo_id.setText("0");

        combo_Data.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_Data.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_DataItemStateChanged(evt);
            }
        });

        jLabel7.setText("Data:");

        Data_id.setForeground(new java.awt.Color(204, 204, 204));
        Data_id.setText("0");

        Censo_id.setForeground(new java.awt.Color(204, 204, 204));
        Censo_id.setText("0");

        botao_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N
        botao_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_buscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Total de registros encontrados:");

        total.setEditable(false);
        total.setText("0");

        org.jdesktop.layout.GroupLayout painel_cadastrar_area3Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area3);
        painel_cadastrar_area3.setLayout(painel_cadastrar_area3Layout);
        painel_cadastrar_area3Layout.setHorizontalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .addContainerGap()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel10)
                    .add(jLabel6)
                    .add(jLabel1)
                    .add(jLabel7))
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(combo_Data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(painel_cadastrar_area3Layout.createSequentialGroup()
                                    .add(jLabel2)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(total, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(painel_cadastrar_area3Layout.createSequentialGroup()
                                    .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(combo_Sexo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(combo_Especie, 0, 188, Short.MAX_VALUE))
                                    .add(18, 18, 18)
                                    .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(combo_Area, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(combo_Status, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(49, 49, 49)
                                    .add(botao_buscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(campo_quantidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Censo_id)
                        .add(5, 5, 5)
                        .add(Especie_id)
                        .add(5, 5, 5)
                        .add(Status_id)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Area_id)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Sexo_id, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Data_id)))
                .addContainerGap())
        );
        painel_cadastrar_area3Layout.setVerticalGroup(
            painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(painel_cadastrar_area3Layout.createSequentialGroup()
                        .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(combo_Especie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel1))
                                .add(4, 4, 4)
                                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel6)
                                    .add(combo_Sexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel7)
                                    .add(combo_Data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(painel_cadastrar_area3Layout.createSequentialGroup()
                                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel3)
                                    .add(combo_Status, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel5)
                                    .add(combo_Area, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(painel_cadastrar_area3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(campo_quantidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Especie_id)
                            .add(Status_id)
                            .add(Area_id)
                            .add(Sexo_id)
                            .add(Censo_id)
                            .add(Data_id)
                            .add(jLabel2)
                            .add(total, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(botao_buscar))
                .add(33, 33, 33))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Data", "Espécie", "Categoria", "Área", "Sexo", "Quantidade", "Animal", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setDragEnabled(true);
        tabela.setRowHeight(25);
        tabela.getTableHeader().setReorderingAllowed(false);
        sp.setViewportView(tabela);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Observação"));

        campo_observacao.setColumns(20);
        campo_observacao.setRows(5);
        jScrollPane1.setViewportView(campo_observacao);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        painel_cadastrar_area9.setBackground(new java.awt.Color(204, 204, 204));
        painel_cadastrar_area9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        voltar.setBackground(new java.awt.Color(204, 204, 204));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.png"))); // NOI18N
        voltar.setToolTipText("Voltar");
        voltar.setBorder(null);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painel_cadastrar_area9Layout = new org.jdesktop.layout.GroupLayout(painel_cadastrar_area9);
        painel_cadastrar_area9.setLayout(painel_cadastrar_area9Layout);
        painel_cadastrar_area9Layout.setHorizontalGroup(
            painel_cadastrar_area9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel_cadastrar_area9Layout.createSequentialGroup()
                .add(voltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 1060, Short.MAX_VALUE))
        );
        painel_cadastrar_area9Layout.setVerticalGroup(
            painel_cadastrar_area9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(voltar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
            .add(painel_cadastrar_area9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(painel_cadastrar_area9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(painel_cadastrar_area3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void combo_EspecieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_EspecieItemStateChanged
        // TODO add your handling code here:
        Especie_id.setText(String.valueOf(bd_Especie.getEspecieIDNome((String)combo_Especie.getSelectedItem())));
}//GEN-LAST:event_combo_EspecieItemStateChanged

    private void combo_StatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_StatusItemStateChanged
        // TODO add your handling code here:
        Status_id.setText(String.valueOf(bd_Status.getStatusIDNome((String)combo_Status.getSelectedItem())));
}//GEN-LAST:event_combo_StatusItemStateChanged

    private void combo_AreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_AreaItemStateChanged
        try {
            // TODO add your handling code here:
            Area_id.setText(String.valueOf(bd_Area.getAreaIDNome((String)combo_Area.getSelectedItem())));
        } catch (SQLException ex) {
            Logger.getLogger(FiltroCenso.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_combo_AreaItemStateChanged

    private void combo_SexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_SexoItemStateChanged
        // TODO add your handling code here:
        Sexo_id.setText(String.valueOf(bd_Sexo.getSexoIDNome((String)combo_Sexo.getSelectedItem())));
}//GEN-LAST:event_combo_SexoItemStateChanged

    private void combo_DataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_DataItemStateChanged
        try {
            // TODO add your handling code here:
            Data_id.setText(String.valueOf(bd_Data.getDataIDNome((String)combo_Data.getSelectedItem())));
        } catch (SQLException ex) {
            Logger.getLogger(FiltroCenso.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_combo_DataItemStateChanged

    private void botao_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_buscarActionPerformed
        // TODO add your handling code here:
        Buscar();
}//GEN-LAST:event_botao_buscarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        kernel.Tela(38, kernel, 0, null, null);
    }//GEN-LAST:event_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area_id;
    private javax.swing.JLabel Censo_id;
    private javax.swing.JLabel Data_id;
    private javax.swing.JLabel Especie_id;
    private javax.swing.JLabel Sexo_id;
    private javax.swing.JLabel Status_id;
    private javax.swing.JButton botao_buscar;
    private javax.swing.JTextArea campo_observacao;
    private javax.swing.JTextField campo_quantidade;
    private javax.swing.JComboBox combo_Area;
    private javax.swing.JComboBox combo_Data;
    private javax.swing.JComboBox combo_Especie;
    private javax.swing.JComboBox combo_Sexo;
    private javax.swing.JComboBox combo_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painel_cadastrar_area3;
    private javax.swing.JPanel painel_cadastrar_area9;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField total;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    private void PreecherFormulario() {
     
        /********* PREENCHENDO O VETOR Especie *************/                
        Especie[] Especie_vetor = null;
        try {
                Especie_vetor = bd_Especie.getEspecies();
            } catch (SQLException exx) {
                Logger.getLogger(CadastrarAnimal.class.getName()).log(Level.SEVERE, null, exx);
            }
        String dados[] = new String[(Especie_vetor.length)+1];

        obj_Especie = new Especie();
        int pos = 0;
        for(int i=0; i < Especie_vetor.length; i++){
            obj_Especie = (Especie)Especie_vetor[i];
            if(i==0){
                dados[i] = "Escolha";
                Especie_id.setText(String.valueOf(0));
            }
            dados[i+1] = String.valueOf(obj_Especie.getNome()).toUpperCase();            
        }
        combo_Especie.setModel(new javax.swing.DefaultComboBoxModel(dados));        
        
        if(acao!=0){
            combo_Especie.setSelectedIndex(pos);
        }       
        /*****************************************************************/
        /********* PREENCHENDO O VETOR Status *************/        
        Status[] Status_vetor = null;
        try {
                Status_vetor = bd_Status.getStatuss();
            } catch (SQLException exx) {
                Logger.getLogger(CadastrarCenso.class.getName()).log(Level.SEVERE, null, exx);
            }
        String dados2[] = new String[(Status_vetor.length)+1];

        obj_Status = new Status();
        int pos2 = 0;
        for(int i=0; i < Status_vetor.length; i++){
            obj_Status = (Status)Status_vetor[i];            
            if(i==0){
              dados2[i] = "Escolha";
              Status_id.setText(String.valueOf(0));
            }
            dados2[i+1] = String.valueOf(obj_Status.getNome()).toUpperCase();                
        }
        combo_Status.setModel(new javax.swing.DefaultComboBoxModel(dados2));        
        
        if(acao!=0){
            combo_Status.setSelectedIndex(pos2);
        }       
        /*****************************************************************/
        /********* PREENCHENDO O VETOR Area *************/                
        Area[] Area_vetor = null;
        try {
                Area_vetor = bd_Area.getAreas();
            } catch (SQLException exx) {
                Logger.getLogger(CadastrarAnimal.class.getName()).log(Level.SEVERE, null, exx);
            }
        String dados3[] = new String[(Area_vetor.length)+1];

        obj_Area = new Area();
        int pos3 = 0;
        for(int i=0; i < Area_vetor.length; i++){
            obj_Area = (Area)Area_vetor[i];
            if(i==0){
                dados3[i] = "Escolha";
                Area_id.setText(String.valueOf(0));
            }
            dados3[i+1] = String.valueOf(obj_Area.getNome()).toUpperCase();
        }
        combo_Area.setModel(new javax.swing.DefaultComboBoxModel(dados3));        
        
        if(acao!=0){
            combo_Area.setSelectedIndex(pos3);
        }       
        /*****************************************************************/
        /********* PREENCHENDO O VETOR Sexo *************/   
        Sexo[] Sexo_vetor = null;
        try {
                Sexo_vetor = bd_Sexo.getSexos();
            } catch (SQLException exx) {
                Logger.getLogger(CadastrarAnimal.class.getName()).log(Level.SEVERE, null, exx);
            }
        String dados4[] = new String[(Sexo_vetor.length)+1];

        obj_Sexo = new Sexo();
        int pos4 = 0;
        for(int i=0; i < Sexo_vetor.length; i++){
            obj_Sexo = (Sexo)Sexo_vetor[i];
            if(i==0){
                dados4[i] = "Escolha";
                Sexo_id.setText(String.valueOf(0));
            }
            dados4[i+1] = String.valueOf(obj_Sexo.getNome()).toUpperCase();
        }
        combo_Sexo.setModel(new javax.swing.DefaultComboBoxModel(dados4));        
        
        if(acao!=0){
            combo_Sexo.setSelectedIndex(pos4);
        }       
        /*****************************************************************/
       /********* PREENCHENDO O VETOR Data *************/   
        Data[] Data_vetor = null;
        try {
                Data_vetor = bd_Data.getDatas();
            } catch (SQLException exx) {
                Logger.getLogger(CadastrarCenso.class.getName()).log(Level.SEVERE, null, exx);
            }
        String dados5[] = new String[(Data_vetor.length)+1];

        obj_Data = new Data();
        int pos5 = 0;
        for(int i=0; i < Data_vetor.length; i++){
            obj_Data = (Data)Data_vetor[i];            
            if(i==0){
                dados5[i] = "Escolha";
                Data_id.setText(String.valueOf(0));
            }
            dados5[i+1] = String.valueOf(new SimpleDateFormat("dd/MM/yyyy").format(obj_Data.getData()));
        }
        combo_Data.setModel(new javax.swing.DefaultComboBoxModel(dados5));        
        
        if(acao!=0){
            combo_Data.setSelectedIndex(pos5);
        }       
        /*****************************************************************/
    }

    private void Buscar() {
            obj_Censo       = new Censo();
            obj_Especie     = new Especie();        
            obj_Status      = new Status();
            obj_Sexo        = new Sexo();
            obj_Area        = new Area();
            obj_Data        = new Data();
            obj_Tag         = new Tag();          
            /********************* SETANDO DADOS CENSO ***********************/
            //SETANDO DADOS DO Censo               
            obj_Censo.setQuantidade(Integer.parseInt((campo_quantidade.getText().equals("")?"0":campo_quantidade.getText())));                         
            
            //SETANDO ESPECIE
            if(!Especie_id.getText().equals("0")){
                obj_Especie.setEspecie_id(Integer.parseInt(Especie_id.getText()));            
                obj_Censo.setEspecie(obj_Especie);
            }
            
            //SETANDO Status
            if(!Status_id.getText().equals("0")){
                obj_Status.setStatus_id(Integer.parseInt(Status_id.getText()));            
                obj_Censo.setStatus(obj_Status);
            }
            
            //SETANDO SEXO
            if(!Sexo_id.getText().equals("0")){
                obj_Sexo.setSexo_id(Integer.parseInt(Sexo_id.getText()));            
                obj_Censo.setSexo(obj_Sexo);
            }
            
            //SETANDO AREA
            if(!Area_id.getText().equals("0")){
                obj_Area.setArea_id(Integer.parseInt(Area_id.getText()));            
                obj_Censo.setArea(obj_Area);
            }
            
            //SETANDO DATA
            if(!Data_id.getText().equals("0")){
                obj_Data.setData_id(Integer.parseInt(Data_id.getText()));            
                obj_Censo.setData(obj_Data);    
            }
            /***************************************************************/
            //PREECHENDO A TABELA Censo                
        Censo[] Censo_vetor = null;
        try {
            //VERIFICAR SE É BUSCA OU NÃO        
            Censo_vetor = bd_Censo.getFiltro(obj_Censo);
        } catch (SQLException ex2) {
            Logger.getLogger(CadastrarCenso.class.getName()).log(Level.SEVERE, null, ex2);
        }
        
        //SETANDO O TOTAL DE REGISTROS ACHADOS
        total.setText(String.valueOf(Censo_vetor.length));
        int quantidade = 0;
        String dados[][] = new String[Censo_vetor.length][10];
        obj_Censo = new Censo();
        for(int i=0; i < Censo_vetor.length; i++){
            obj_Censo = (Censo)Censo_vetor[i];
            dados[i][0] = String.valueOf(obj_Censo.getCenso_id());            
            dados[i][1] = new SimpleDateFormat("dd/MM/yyyy").format(obj_Censo.getData().getData());
            dados[i][2] = ((obj_Censo.getEspecie()!=null)?String.valueOf(obj_Censo.getEspecie().getNome()):"");
            dados[i][3] = ((obj_Censo.getStatus()!=null)?String.valueOf(obj_Censo.getStatus().getNome()):"");            
            dados[i][4] = String.valueOf(obj_Censo.getArea().getNome());
            dados[i][5] = ((obj_Censo.getSexo()!=null)?String.valueOf(obj_Censo.getSexo().getNome()):"");              
            dados[i][6] = String.valueOf(obj_Censo.getQuantidade()); 
            dados[i][7] = (((bd_AnimalCenso.getTotal(Integer.parseInt(Censo_id.getText())))>0)?"Possui":"Não possui");                        
            quantidade  += obj_Censo.getQuantidade();
        }
        //campo_observacao.setText(bd_Censo_Observacao.getObservacao(Integer.parseInt(Data_id.getText()),Integer.parseInt(Area_id.getText())));
        //SETANDO O TOTAL DE REGISTROS ACHADOS
        campo_quantidade.setText(String.valueOf(quantidade));
        campo_observacao.setText("");
        
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            dados,
            new String [] {"Cod", "Data","Espécie","Status","Area","Sexo","Quantidade","Animal"}){
            Class[] types = new Class [] {
                java.lang.String.class, 
                java.lang.String.class,
                java.lang.String.class, 
                java.lang.String.class,
                java.lang.String.class, 
                java.lang.String.class,                               
                java.lang.String.class,  
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
      
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(100);        
        tabela.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);        
        tabela.getColumnModel().getColumn(4).setPreferredWidth(200);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(7).setPreferredWidth(100);        
        
        
        tabela.setDragEnabled(true);
        sp.setViewportView(tabela);        
        
            
    }

}
